// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_GB": &dictionary{index: en_GBIndex, data: en_GBData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("zh-TW")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"不支援 12 組以上的助記詞":   12,
	"助記詞":              4,
	"助記詞：":             7,
	"匹配":               9,
	"匹配中":              13,
	"已知":               6,
	"有效組合":             15,
	"未知":               5,
	"無效的 TRC20 USDT地址": 11,
	"無法匹配助記詞":          14,
	"複製貼上註記詞，將不確定的助記詞以＊代替．": 3,
	"設定":    0,
	"語系":    1,
	"說明":    2,
	"警告":    10,
	"錢包地址：": 8,
}

var en_GBIndex = []uint32{ // 17 elements
	0x00000000, 0x00000008, 0x00000011, 0x00000016,
	0x0000005a, 0x00000062, 0x0000006a, 0x00000070,
	0x00000078, 0x00000083, 0x00000089, 0x00000091,
	0x000000a7, 0x000000be, 0x000000c7, 0x000000d2,
	0x000000e0,
} // Size: 92 bytes

const en_GBData string = "" + // Size: 224 bytes
	"\x02Setting\x02Language\x02Info\x02Copy and paste mnemonic phrase and re" +
	"place unknown phrases with ＊\x02Phrases\x02Unknown\x02Known\x02Phrases" +
	"\x02Address：\x02Match\x02Warning\x02Invalid TRC20 Address\x02Only accept" +
	" 12 phrases\x02Matching\x02No Matches\x02Valid Phrases"

var zh_CNIndex = []uint32{ // 17 elements
	0x00000000, 0x00000007, 0x0000000e, 0x00000015,
	0x00000055, 0x0000005f, 0x00000066, 0x0000006d,
	0x0000007a, 0x0000008a, 0x00000091, 0x00000098,
	0x000000b3, 0x000000d6, 0x000000e0, 0x000000f6,
	0x00000103,
} // Size: 92 bytes

const zh_CNData string = "" + // Size: 259 bytes
	"\x02设定\x02语系\x02说明\x02复制贴上注记词，将不确定的助记词以＊代替．\x02助记词\x02未知\x02已知\x02助记词：" +
	"\x02钱包地址：\x02匹配\x02警告\x02无效的 TRC20 USDT地址\x02不支援 12 组以上的助记词\x02匹配中\x02无法" +
	"匹配助记词\x02有效组合"

	// Total table size 667 bytes (0KiB); checksum: F0215F1
