name: Create release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  create:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
    steps:
      - name: Create release
        id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build:
    name: ${{ matrix.os }}-hosted
    needs: create
    env:
      buildDir: '${{ github.workspace }}/build'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        arch: [amd64, arm64]
        exclude:
        - os: windows-latest
          arch: arm64
        - os: ubuntu-latest
          arch: arm64
    steps:
      - name: Checks-out
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - name: Install X11 dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install -y libx11-dev libxcursor-dev \
            libxrandr-dev libxinerama-dev libxi-dev \
            libglx-dev libgl1-mesa-dev libxxf86vm-dev \
            libgtk-3-dev
      - run: make arch-${{ matrix.arch }}
      - name: Pack mac app on macOS
        if: runner.os == 'macOS'
        run: make osx-app
      - name: Compress
        uses: papeloto/action-zip@v1
        with:
          files: build/${{ matrix.arch }}
          dest: lua-table-editor-${{ runner.os }}-${{ matrix.arch }}.zip
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./lua-table-editor-${{ runner.os }}-${{ matrix.arch }}.zip
          asset_name: lua-table-editor-${{ runner.os }}-${{ matrix.arch }}.zip
          asset_content_type: application/zip